from typing import Protocol

from openlolo.domain.models import Binding, CaptureOptions, Frame


class DeviceBackend(Protocol):
    """One CoreDevice-backed phone: screen, touch, keyboard, buttons and device information.

    The transport (USB or Wi-Fi) is part of the binding; callers never see it.
    """

    async def connect(self, binding: Binding) -> dict: ...
    async def disconnect(self) -> dict: ...
    async def unbind(self) -> dict: ...
    async def capture(self, binding: Binding, options: CaptureOptions) -> Frame: ...
    async def begin(self, binding: Binding, kinds: list[str] | None = None) -> str: ...
    async def report(self, generation: str, kind: str, value: list) -> None: ...
    async def gesture(self, generation: str, points: list) -> dict:
        """One touch gesture, ``[t, state, x, y]`` points paced by the backend on its own clock.
        Returns report count and cadence (``median_interval_ms``, ``max_gap_ms``)."""
        ...

    async def release_all(self) -> None: ...
    async def health(self) -> dict: ...
    async def verify(self, binding: Binding) -> dict: ...
    async def recover(self, binding: Binding) -> dict: ...
    async def list_apps(self, binding: Binding) -> list[dict]: ...
    async def launch_app(
        self, binding: Binding, bundle_id: str, url: str | None = None, kill_existing: bool = False
    ) -> dict:
        """Foreground the app, optionally handing it a URL to open. Returns the process identifier."""
        ...

    async def device_info(self, binding: Binding) -> dict: ...
    async def clipboard_get(self, binding: Binding) -> dict:
        """The general pasteboard as {"text": str | None, "change_count": int | None}."""
        ...

    async def clipboard_set(self, binding: Binding, text: str) -> dict:
        """Replace the general pasteboard with UTF-8 text and read it back to confirm."""
        ...

    # Onboarding: these never require a binding and never select a phone implicitly.
    async def discover(self) -> dict: ...

    async def usb_phones(self) -> list[dict]:
        """Phones on the cable: udid, product_type, product_version (None when unreadable)."""
        ...

    async def wifi_addresses(self, udid: str) -> list[str]:
        """IP addresses the paired phone advertises on the LAN right now; empty when unknown."""
        return []

    async def pair(self, udid: str) -> dict: ...
    async def developer_mode(self, udid: str) -> dict: ...
    async def mount_ddi(self) -> dict: ...
