from typing import Protocol


class NetworkBackend(Protocol):
    """Wi-Fi management on the box (NetworkManager on a Pi, a fake in the simulator).

    Profiles this software creates carry the ``openlolo-`` prefix; provisioning never removes
    a profile it did not create unless the owner explicitly forces it (PRD FR-07).
    """

    async def health(self) -> dict: ...

    async def status(self) -> dict: ...

    async def scan(self) -> list[dict]: ...

    async def saved(self) -> list[dict]: ...

    async def connect(self, ssid: str, psk: str, name: str, timeout: float = 45) -> None: ...

    async def forget(self, name: str, force: bool = False) -> None: ...

    async def restore_connection(self, name: str) -> None: ...

    async def remove_legacy_hotspot(self) -> None: ...
