from typing import Protocol


class OperationJournal(Protocol):
    def reserve(self, operation_id: str, owner: str, kind: str, payload: dict) -> tuple[dict, bool]: ...
    def update(self, operation_id: str, state: str, result: dict | None = None) -> dict: ...
    def get(self, operation_id: str, owner: str) -> dict: ...
    def list_operations(self, limit: int = 50, before: float | None = None) -> list[dict]: ...
    def page_operations(self, limit: int = 20, cursor: str | None = None) -> dict: ...
    def journal_revision(self) -> int: ...
    def label_owner(self, owner: str, label: str) -> None: ...
